// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JW9K8LGha2aoaSDZGGgppzgHSeKQH8g',
    appId: '1:928939982821:web:c2b9148daab6f15255790c',
    messagingSenderId: '928939982821',
    projectId: 'apptapgym-3152f',
    authDomain: 'apptapgym-3152f.firebaseapp.com',
    storageBucket: 'apptapgym-3152f.appspot.com',
    measurementId: 'G-BBT9B6GGF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGJdZRm-PHrhZcQpDOsBIVC-yMHquRKY',
    appId: '1:928939982821:android:44ba2218ea13985a55790c',
    messagingSenderId: '928939982821',
    projectId: 'apptapgym-3152f',
    storageBucket: 'apptapgym-3152f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZjhYcvMGbMA3wW7HWZcv6woxzc9lJoY',
    appId: '1:928939982821:ios:8dea6492aadafe7855790c',
    messagingSenderId: '928939982821',
    projectId: 'apptapgym-3152f',
    storageBucket: 'apptapgym-3152f.appspot.com',
    iosClientId: '928939982821-hiev9hqpgis1vvh978d08mkt82o8qfp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.doanTapgymtainha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKZjhYcvMGbMA3wW7HWZcv6woxzc9lJoY',
    appId: '1:928939982821:ios:8dea6492aadafe7855790c',
    messagingSenderId: '928939982821',
    projectId: 'apptapgym-3152f',
    storageBucket: 'apptapgym-3152f.appspot.com',
    iosClientId: '928939982821-hiev9hqpgis1vvh978d08mkt82o8qfp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.doanTapgymtainha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2JW9K8LGha2aoaSDZGGgppzgHSeKQH8g',
    appId: '1:928939982821:web:64f1a88911d2acf455790c',
    messagingSenderId: '928939982821',
    projectId: 'apptapgym-3152f',
    authDomain: 'apptapgym-3152f.firebaseapp.com',
    storageBucket: 'apptapgym-3152f.appspot.com',
    measurementId: 'G-2G0VDNKM61',
  );
}
